name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: |
          11
          17
          21
    - name: Build with Maven
      run: mvn --errors --batch-mode clean org.jacoco:jacoco-maven-plugin:prepare-agent install
    - name: Sonar
      if: ${{ env.SONAR_TOKEN != null }}
      run: mvn --errors --batch-mode -Dsonar.token=$SONAR_TOKEN sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: always()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
